<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lytex</string>
	</array>
	<key>name</key>
	<string>LilyPond Book</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>((\\)begin{lilypond}(\[.*\])?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((\\)end{lilypond})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lytex.lilypond.lytex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lilypond</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((\\)lilypond(\[.*\])?)({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.lilypond</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.python.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.python.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lytex.lilypond.lytex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lilypond2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>lilypond2</key>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.python.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.python.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lytex.lilypond2.lytex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lilypond2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lytex</string>
	<key>uuid</key>
	<string>ed599d76-5c58-49ff-b1a7-63ccf52d0623</string>
</dict>
</plist>
