<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lytex</string>
	</array>
	<key>name</key>
	<string>LilyPond Book</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(((\\)begin)\s*({)\s*lilypond\s*(})\s*((\[).*(\]))?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.general.tex.lilypond</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.tex.lilypond</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.tex.lilypond</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.brackets.tex.lilypond</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.brackets.tex.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(((\\)end)\s*({)\s*lilypond\s*(}))</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.general.tex.lilypond</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.tex.lilypond</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.tex.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lytex.lilypond</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lilypond</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((\\lilypond)\s*((\[).*(\])\s*)?)({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.general.tex.lilypond</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.brackets.tex.lilypond</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.brackets.tex.lilypond</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.tex.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.group.tex.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lytex.lilypond</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lilypond</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>lilypond</key>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.python.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.python.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lytex.lilypond</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lilypond</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tex.latex.lytex</string>
	<key>uuid</key>
	<string>ed599d76-5c58-49ff-b1a7-63ccf52d0623</string>
</dict>
</plist>
